### ISSUE TITLE
Symbol Support

### ISSUE THREAD

**Issue by Craigtut** [lokalise/lokalise-sketchplugin#1]
Congrats on the recent release guys. 

Is support for nested symbols in the pipeline at all? Right now it looks like symbols themselves aren't supported yet; is this correct?

**Comment by andrewLab-lokalise** [comment]
Hi, Craig

Thank you :)

Symbol support is currently among the most requested improvement. We are focused to deliver it in upcoming releases.

**Comment by Craigtut** [comment]
Okay, thanks @andrewLab-lokalise

**Comment by andrewLab-lokalise** [comment]
Hey @Craigtut,

We just released a new version with Symbol support:
https://github.com/lokalise/lokalise-sketchplugin/releases/tag/v1.1.0

Would appreciate your feedback :)

**Comment by Craigtut** [comment]
@andrewLab-lokalise - The plugin still doesn't quite work as needed. It appears to only pick up one text layer from a symbol. As soon as I add multiple text layers to a symbol, I cannot select the other newly added layers. Is this a bug or intentional functionality?

See video and demo file:  https://drive.google.com/drive/folders/1A1qfhCqpKN-rWKectbt2QcjToUzv7r-G?usp=sharing

**Comment by andrewLab-lokalise** [comment]
@Craigtut ,

Thank you for your feedback.

The bugfix is already in progress, we are addressing the issue in the upcoming release.

**Comment by andrewLab-lokalise** [comment]
Hey @Craigtut,

We just released a new version addressing the issue of multiple text layers in symbols:
https://github.com/lokalise/lokalise-sketchplugin/releases/tag/v1.1.1
